version: '3.2'
services:
  app:
    environment:
      - ENV_TYPE
    restart: always
    build:
      context: app
      args:
        - user=elspeth
    image: python-tdd_app_${ENV_TYPE}
    volumes:
      - type: volume
        source: static
        target: /home/elspeth/sites/static
    networks:
      netty:
  webserver:
    environment:
      - DOMAIN
    restart: always
    build:
      context: nginx
    volumes:
      - type: volume
        source: static
        target: /opt/app/static
    ports:
    - target: 80
      published: 80
    networks:
      netty:
networks:
  netty:
volumes:
  static:
