version: '3.7'
services:
  app:
    container_name: python-tdd_app_ovrd
    volumes:
      - type: bind
        source: ./app
        target: /home/elspeth/sites/
  webserver:
    container_name: python-tdd_webserver_ovrd
