version: '3.7'
services:
  app:
    env_file:
      - ./.env
    build:
      context: app
      args:
        - user=elspeth
    volumes:
      - type: volume
        source: static
        target: /home/elspeth/sites/static
    networks:
      netty:
  webserver:
    env_file:
      - ./.env
    build:
      context: nginx
    volumes:
      - type: volume
        source: static
        target: /opt/app/static
    ports:
    - target: 80
      published: 80
    networks:
      netty:
networks:
  netty:
volumes:
  static:
