version: '3.2'
services:
  app:
    environment:
      - ENV_TYPE
    build:
      context: .
      args:
        - ENV_TYPE
    networks:
      netty:
        ipv4_address: 172.16.0.11
  webserver:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./nginx/static
        target: /opt/app/static
    networks:
      netty:
        ipv4_address: 172.16.0.10
networks:
  netty:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          # gateway: 172.16.0.1 # gateway somehow causes an error
