version: '3.2'
services:
  app:
    environment:
      - ENV_TYPE
    restart: always
    build:
      context: app
      args:
        - user=elspeth
    image: python-tdd_app_${ENV_TYPE}
    volumes:
      - type: volume
        source: static
        target: /home/elspeth/sites/static
    networks:
      netty:
        ipv4_address: 172.16.0.11
  webserver:
    restart: always
    build:
      context: nginx
    volumes:
      - type: volume
        source: static
        target: /opt/app/static
    networks:
      netty:
        ipv4_address: 172.16.0.10
networks:
  netty:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          # gateway: 172.16.0.1 # gateway somehow causes an error
volumes:
  static:
