version: '3.7'
services:
  app:
    env_file:
      - ./.env
    build:
      context: app
      args:
        - user=elspeth
    networks:
      netty:
  webserver:
    env_file:
      - ./.env
    build:
      context: nginx
    ports:
    - target: 80
      published: 80
    networks:
      netty:
networks:
  netty:
